enterpriseCertification="/html/body/div/div/div[2]/div[1]/ul/div[2]/li/ul/li[3]/span[1]"#企业资质
append="/html/body/div/div/div[2]/div[2]/div[2]/form/div[7]/div/button"#新增
enterpriseName="/html/body/div[1]/div/div[2]/div[2]/div[2]/div/div/form/div[1]/div/div/div/input"#企业名称
enterpriseMessage="/html/body/div[2]/div[1]/div[1]/ul/li[1]"#企业信息
certificateName="/html/body/div[1]/div/div[2]/div[2]/div[2]/div/div/form/div[3]/div/div[1]/input"#证书名称
certificateNumber="/html/body/div[1]/div/div[2]/div[2]/div[2]/div/div/form/div[4]/div/div[1]/input"#证书编号
certificationClass="/html/body/div[1]/div/div[2]/div[2]/div[2]/div/div/form/div[5]/div/div/div[1]/span/input"#资质等级
certificateSelect="/html/body/div[1]/div/div[2]/div[2]/div[2]/div/div/form/div[5]/div/div/div[2]/ul[2]/li[2]"#证书选择
validity="/html/body/div[1]/div/div[2]/div[2]/div[2]/div/div/form/div[6]/div/label[2]/span[1]/span"#有效期
affirm="/html/body/div[1]/div/div[2]/div[2]/div[2]/div/div/form/div[9]/div/button[2]"#确认
picture = "/html/body/div/div/div[2]/div[2]/div[2]/div/div/form/div[7]/div/div/div/input"#图片
picture_position = "C:\\Users\\111\\Pictures\\Saved Pictures\\background.png"#图片url