#漳州小额正式环境配置
username:
  18567985980
  17600228350
  15260621329
  15216189856
enterpriseName:
  漳州招投标测试企业
  国函通科技有限公司
  厦建设发展有限公司
  农大侠（厦门）信息技术有限公司
username1:
  15212345678
  15287654321
  15000000000
password:
  ndx111
  ndx111
url:
  deal_login_url: https://user.xiaoeztb.com/#/login #交易平台登录地址
  expert_login_url: https://expert.xiaoeztb.com/#/login # 专家端登陆地址
  expert_projectList_url: https://expert.xiaoeztb.com/#/projectList  # 专家端选择项目列表地址
  extract_login_url: https://drawexpert.xiaoeztb.com/#/  # 抽取系统登录地址
  workbench_url: https://user.xiaoeztb.com/#/  # 工作台地址
  back_url: https://oper.xiaoeztb.com/#/login  # 总后台
extract_username:
  15212345678
  15312345678
  15412345678
extract_password: ndx111
marginApplyWay: 0
tenderMan: 厦门翔安建设发展有限公司  # 招标代理创建项目时，填写的招标人
tenderManUnicode: 91350213751625538W  # 招标代理创建项目时，填写的社会统一信用代码
tenderAgentName: 厦门城市开发建设有限公司