#淮安正式环境配置
username:
  15216189856
  17306010296
  18106099208
  17750626025

enterpriseName:
  农大侠（厦门）信息技术有限公司
  国函通科技有限公司
  江西湘昌建设有限公司
  江西省本善建筑有限公司

username1:
  15260621329
  15287654321
  13313707910

password:
  ndx111
  ndx111

url:
  deal_login_url: https://user.biaohantong.com/#/login #交易平台登录地址
  expert_login_url: https://expert.biaohantong.com/#/login # 专家端登陆地址
  expert_projectList_url: https://expert.biaohantong.com/#/projectList  # 专家端选择项目列表地址
  extract_login_url: https://drawexpert.biaohantong.com/#/  # 抽取系统登录地址
  workbench_url: https://user.biaohantong.com/#/  # 工作台地址
  back_url: https://oper.biaohantong.com/#/login  # 总后台

extract_username:
  15212345678
  15312345678
  15412345678

extract_password: ndx111
marginApplyWay: 0
tenderMan: 厦门翔安建设发展有限公司  # 招标代理创建项目时，填写的招标人
tenderManUnicode: 91350213751625538W  # 招标代理创建项目时，填写的社会统一信用代码
tenderAgentName: 以招标公告为准