#三明正式环境配置
username:
  17759210504
  13313707910
  15216189856
  15805935665
enterpriseName:
  测试公司名称
  以招标公告为准
  农大侠（厦门）信息技术有限公司
  国函通科技有限公司
username1:
  13026824439
  15287654321
  15260621329
password:
  ndx111
  ndx111
url:
  deal_login_url: https://user.minhztb.com/#/login #交易平台登录地址
  expert_login_url: https://expert.minhztb.com/#/login # 专家端登陆地址
  expert_projectList_url: https://expert.minhztb.com/#/projectList  # 专家端选择项目列表地址
  extract_login_url: https://drawexpert.minhztb.com/#/  # 抽取系统登录地址
  workbench_url: https://user.minhztb.com/#/  # 工作台地址
  back_url: https://oper.minhztb.com/#/login  # 总后台
extract_username: 15212345678
extract_password: ndx111
marginApplyWay: 0
tenderMan: 测试企业  # 招标代理创建项目时，填写的招标人
tenderManUnicode: 4585452SDFGVCD454  # 招标代理创建项目时，填写的社会统一信用代码
tenderAgentName: 测试企业