#小额漳州测试环境的配置信息
username:
  15222222222
  15233333333
  15287654321
  15255555555
  15244444444
  18567985980
  17600228350
  15260621329
  15216189856
enterpriseName:
  福建尤建科技有限公司
  福建省佳美集团公司厦门分公司
  江西湘昌建设有限公司
  江西省本善建筑有限公司
  江西九润建设工程有限公司
  内部测试企业号
  国函通科技有限公司
  厦建设发展有限公司
  农大侠（厦门）信息技术有限公司
username1:
  15212345678
  15287654321
  13412841346
password:
  ndx111
  ndx111
url:
  deal_login_url: http://user.jiaoyi.com/#/login #交易平台登录地址
  expert_login_url: http://expert.jiaoyi.com/#/login # 专家端登陆地址
  expert_projectList_url: http://expert.jiaoyi.com/#/projectList  # 专家端选择项目列表地址
  extract_login_url: http://drawexpert.jiaoyi.com/#/  # 抽取系统登录地址
  workbench_url: http://user.jiaoyi.com/#/  # 工作台地址
  back_url: http://oper.jiaoyi.com/#/login  # 总后台

extract_username:
  15212345678
  15312345678
  15412345678
extract_password: ndx111
marginApplyWay: 2
tenderMan: 江西鸿业生态环境建设集团有限公司 # 招标代理创建项目时，填写的招标人
tenderManUnicode: 91350200MA2YNRF9XT3  # 招标代理创建项目时，填写的社会统一信用代码
tenderAgentName: 甘肃省胸补声蕊秘咨询股份有限公司




